WebStore/WebApp/Controllers/BrandsViewController.cs
using System;
using System.Threading.Tasks;
using Contracts.BLL.App;
using Extensions;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class BrandsViewController : Controller
    {
        private readonly IAppBLL _bll;

        public BrandsViewController(IAppBLL bll)
        {
            _bll = bll;
        }

        // GET: BrandsView
        public async Task<IActionResult> Index()
        {
            return View(await _bll.BrandService.AllAsync());
        }
        
        // GET: BrandsView/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _bll.BrandService
                .FirstOrDefaultAsync((Guid)id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }
    }
}

WebStore/WebApp/Controllers/ItemsViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.App.DTO;
using Contracts.BLL.App;
using Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class ItemsViewController : Controller
    {
        private readonly IAppBLL _bll;

        public ItemsViewController(IAppBLL bll)
        {
            _bll = bll;
        }

        /// <summary>
        /// Index method , creates view model for view, collects all items, brands and categories
        /// </summary>
        /// <param name="brandId">comes from BrandsView -> </param>
        /// <returns>All products</returns>
        [HttpGet]
        public async Task<IActionResult> Index(Guid? brandId = null)
        {
            var vm = new ItemsViewViewModel
            {
                CategorySelectList = new MultiSelectList(
                    await _bll.CategoryService.GetAllSubCategoriesAsync(), nameof(Category.Id),
                    nameof(Category.Name)),
                BrandSelectList = new MultiSelectList(
                    await _bll.BrandService.AllAsync(), nameof(Brand.Id), nameof(Brand.Name))
            };
            vm.Items = await _bll.ItemService.AllAsync("", null,
                (brandId == null) ? null : new List<Guid> {(Guid) brandId});

            return View(vm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(ItemsViewViewModel vm)
        {
            vm.CategorySelectList = new MultiSelectList(
                await _bll.CategoryService.GetAllSubCategoriesAsync(), nameof(Category.Id),
                nameof(Category.Name));
            vm.BrandSelectList = new MultiSelectList(
                await _bll.BrandService.AllAsync(), nameof(Brand.Id), nameof(Brand.Name));
            vm.Items = await _bll.ItemService.AllAsync("", vm.CategoriesFilter, vm.BrandsFilter);

            return View(vm);
        }

        public async Task<IActionResult> AddToCart(Guid? itemId)
        {
            if (itemId == null)
            {
                return NotFound();
            }

            var item = await _bll.ItemService.FirstOrDefaultAsync(itemId.Value);
            var cart = await _bll.CartService.GetCartAsync(User.UserGuidId());

            await _bll.ItemInCartService.AddProduct(item, cart, User.UserGuidId());
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddToWishList(Guid? itemId)
        {
            if (itemId == null)
            {
                return NotFound();
            }

            await _bll.UserWishListService.AddProduct(itemId.Value, User.UserGuidId());
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: Items/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _bll.ItemService
                .FirstOrDefaultAsync((Guid) id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }
    }
}

WebStore/WebApp/Controllers/SearchPageController.cs
using System;
using System.Threading.Tasks;
using BLL.App.DTO;
using Contracts.BLL.App;
using Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class SearchPageController : Controller
    {
        private readonly IAppBLL _bll;

        public SearchPageController(IAppBLL bll)
        {
            _bll = bll;
        }

        // GET
        public async Task<IActionResult> Index(string? search = "")
        {
            search ??= "";
            var vm = new ItemsViewViewModel
            {
                Search = search,
                CategorySelectList = new MultiSelectList(
                    await _bll.CategoryService.GetAllSubCategoriesAsync(), nameof(Category.Id),
                    nameof(Category.Name)),
                BrandSelectList = new MultiSelectList(
                    await _bll.BrandService.AllAsync(), nameof(Brand.Id), nameof(Brand.Name))
            };
            vm.Items = await _bll.ItemService.AllAsync(search);

            return View(vm);        
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(ItemsViewViewModel vm)
        {
            if (vm.Search == null) vm.Search = "";
            vm.CategorySelectList = new MultiSelectList(
                await _bll.CategoryService.GetAllSubCategoriesAsync(), nameof(Category.Id),
                nameof(Category.Name));
            vm.BrandSelectList = new MultiSelectList(
                await _bll.BrandService.AllAsync(), nameof(Brand.Id), nameof(Brand.Name));
            vm.Items = await _bll.ItemService.AllAsync(vm.Search, vm.CategoriesFilter, vm.BrandsFilter);
            
            return View(vm);
        }

        public async Task<IActionResult> AddToCart(Guid? itemId)
        {
            if (itemId == null)
            {
                return NotFound();
            }

            var item = await _bll.ItemService.FirstOrDefaultAsync(itemId.Value);
            var cart = await _bll.CartService.GetCartAsync(User.UserGuidId());

            await _bll.ItemInCartService.AddProduct(item, cart, User.UserGuidId());
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddToWishList(Guid? itemId)
        {
            if (itemId == null)
            {
                return NotFound();
            }

            await _bll.UserWishListService.AddProduct(itemId.Value, User.UserGuidId());
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

WebStore/WebApp/Views/SearchPage/Index.cshtml
@using Extensions
@model ItemsViewViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-xs-12 col-md-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <form asp-action="Index">
            <input hidden="" asp-for="Search" value="@Model.Search"/>
            <div>
                <strong>@Resources.Views.Shared._Layout.Brands</strong>
                <div class="form-group">
                    <select asp-for="BrandsFilter" class="form-control" asp-items="Model.BrandSelectList" multiple="multiple"></select>
                </div>
            </div>
            <div>
                <strong>@Resources.Views.Shared._Layout.Categories</strong>
                <div class="form-group">
                    <select asp-for="CategoriesFilter" class="form-control" asp-items="Model.CategorySelectList" multiple="multiple"></select>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="@Resources.Common.Filter" class="btn btn-primary"/>
            </div>
        </form>
    </div>
    <div class="col-xs-12 col-md-9">
        <div class="row">
            <div class="col-12" style="text-align: center">
                <h4 style="display: inline-block; vertical-align: middle; text-align: right;">
                    @if (string.IsNullOrEmpty(Model.Search))
                    {
                        <text>All results</text>
                    }
                    else
                    {
                        <text>@Resources.Common.ResultsFor <strong>@Model.Search</strong></text>
                    }
                </h4>
            </div>
            @foreach (var item in Model.Items)
            {
                <div class="col-xs-12 col-sm-6 col-lg-4">
                    <div class="card">
                        <a asp-controller="ItemsView" asp-action="Details" asp-route-id="@item.Id">
                            <img class="card-img-top" style="height: 240px;" src="https://cdn.icon-icons.com/icons2/1678/PNG/512/wondicon-ui-free-parcel_111208.png" alt="">
                            <div class="card-body">
                                <p class="card-text">@Html.DisplayFor(modelItem => item.Name) - <a asp-controller="BrandsView" asp-action="Details" asp-route-id="@item.BrandId">@Html.DisplayFor(modelItem => item.Brand!.Name)</a></p>
                                <p class="card-text">@Html.DisplayNameFor(model => item.Price) - @Html.DisplayFor(modelItem => item.Price)$</p>
                            </div>
                        </a>
                        @if (User.IsAuthorized())
                        {
                            <div class="row" style="justify-content:center">
                                <a class="btn btn-primary own-btn own-btn-cart col-10" asp-action="AddToCart" asp-route-itemId="@item.Id"> @Resources.Common.AddToCart</a>
                                <a class="btn btn-secondary own-btn own-btn-wish col-10" asp-action="AddToWishList" asp-route-itemId="@item.Id"> @Resources.Common.AddToWishList</a>
                            </div>
                        }
                    </div>
                </div>
            }
        </div>

    </div>

</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}